import { chdir } from 'process'
import ClientOnly from './components/ClientOnly'
import Navbar from './components/navbar/Navbar'
import './globals.css'
import { Inter, Nunito } from 'next/font/google'
import Modal from './components/modal/Modal'
import RegisterModal from './components/modal/RegisterModal'
import ToasterProvider from './providers/ToasterProvider'
import LoginModal from './components/modal/LoginModal'
import getCurrentUser from './actions/GetCurrentUser'
import RentalModal from './components/modal/RentalModal'
import SearchModal from './components/modal/SearchModal'

const inter = Nunito({ subsets: ['latin'] })

export const metadata = {
  title: 'Airbnb Website',
  description: 'Generated by create next app',
}

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  const currentUser = await getCurrentUser()

  return (
    <html lang="en">
      <body className={inter.className}>
        <ClientOnly>
          <ToasterProvider />
          <RegisterModal />
          <SearchModal />
          <RentalModal />
          <LoginModal />
          <Navbar currentUser = {currentUser}/>
        </ClientOnly>
        <div className='pb-20 pt-28'>
          {children}  
        </div>
      </body>
    </html>
  )
}
